#!/bin/sh

url="https://servicos.receita.fazenda.gov.br/publico/programas/Sped/SpedContabil"
version=$(head -1 debian/changelog | awk -F"[()]" '{print $2}')

rm -f sources/SPEDContabil_linux_x64-*
git annex addurl --file sources/SPEDContabil_linux_x64-${version}.jar $url/SPEDContabil_linux_x64-${version}.jar
