#!/bin/sh

url="https://servicos.receita.fazenda.gov.br/publico/programas/SpedPisCofinsPVA"
version=$(head -1 debian/changelog | awk -F"[()]" '{print $2}')

rm -f sources/EFDContribuicoes_linux_x64-*
git annex addurl --file sources/EFDContribuicoes_linux_x64-${version}.jar $url/EFDContribuicoes_linux_x64-${version}.jar
