#!/bin/sh

url="https://servicos.receita.fazenda.gov.br/publico/programas/Sped/ECF"
version=$(head -1 debian/changelog | awk -F"[()]" '{print $2}')

rm -f sources/PSpedEcf_linux_x64-*
git annex addurl --file sources/SpedEcf_linux_x64-${version}.jar $url/SpedEcf_linux_x64-${version}.jar
